# Created by Oleksandr Sorochynskyi
# On 14 06 18

source("~/IdV/R/neurons.R");


##########################################################################################
# Try Distributional transform



data <- bin_neurons(c(1,2), 4,0);
t1 <- data[1,];
t2 <- data[2,];
u1 <- distributional_transfrom(t1);
u2 <- distributional_transfrom(t2);

(fit_copula(t1,t2,gumbelCopula(),upper=6))
(fitCopula(gumbelCopula(),cbind(u1,u2)))
(fitCopula(claytonCopula(),cbind(u1,u2)))
(fitCopula(rotCopula(claytonCopula()),cbind(u1,u2)))
(fitCopula(normalCopula(),cbind(u1,u2)))
(fitCopula(frankCopula(),cbind(u1,u2)))
(fitCopula(plackettCopula(),cbind(u1,u2)))

fit_copula(t1,t2,rotCopula(claytonCopula()),upper=6);
fit_copula(t1,t2,claytonCopula())
fit_copula(t1,t2,gumbelCopula(),upper=6);
fit_copula(t1,t2,frankCopula())
##########################################################################################
# try looking applying the continuation transform

data <- bin_neurons(c(1,2),4);
t1 <- data[1,] + runif(length(data[1,]))
t2 <- data[2,] + runif(length(data[1,]))

fit <- fitCopula(claytonCopula(),pobs(cbind(t1,t2)));
fit <- fitCopula(gumbelCopula(),pobs(cbind(t1,t2)));
fit <- fitCopula(frankCopula(),pobs(cbind(t1,t2)));
fit <- fitCopula(normalCopula(),pobs(cbind(t1,t2)));

#compare data generated by fits vs real data
samp <- copula_rand_emp(length(t1), cop= fit@copula, x1= t1, x2= t2);
samp <- rCopula(length(t1),fit@copula)

tbl1 <- xyTable(ecdf(t1)(t1),ecdf(t2)(t2));
plot(tbl1$x, tbl1$y, cex=tbl1$number*0.05, main= "Real");

tbl2 <- xyTable(samp[,1], samp[,2]);
plot(tbl2$x, tbl2$y, cex=tbl2$number*0.05, main= "Generated");

##########################################################################################
# look for bottlenecks
t1 <- neurons[3,]
t2 <- neurons[8,]

samp <- copula_rand_emp(10000,frankCopula(0.5),x1=t1,x2=t2);
q1 <- make_quantile(samp[,1])
q2 <- make_quantile(samp[,2])
library(profvis)
profvis({
  copula_loglik_test(samp[,1],samp[,2],indepCopula(),frankCopula(0.5))
});
##########################################################################################
# Test Cramer independance test

t1 <- neurons[3,]
t2 <- neurons[8,]

samp <- copula_rand_emp(10000,frankCopula(0.5),x1=t1,x2=t2);

copula_kramer_indep_test(samp[,1],samp[,2])
##########################################################################################
# More tests for distance criteria

t1 <- neurons[3,]
t2 <- neurons[2,]
# Generate random independat data
samp <- copula_rand_emp(10000,indepCopula(),x1=t1,x2=t2);
# Fit a copula to it
fit <- fit_copula(samp[,1],samp[,2],frankCopula());
afit <- fit_copula(samp[,1],samp[,2],claytonCopula());
copula_distance_test(samp[,1],samp[,2],claytonCopula(afit$par),frankCopula(fit$par));
copula_loglik_test(samp[,1],samp[,2],indepCopula(),frankCopula(1));

##########################################################################################
# Test distance copula choice criteria

t1 <- neurons[3,]
t2 <- neurons[2,]
cdf1 <- ecdf(t1)
cdf2 <- ecdf(t2)
gfit <- fit_copula(t1,t2,gumbelCopula(),upper=6)
cfit <- fit_copula(t1,t2,claytonCopula())
rclaytonCop <- rotCopula(claytonCopula(3),flip=c(TRUE,TRUE))
rcfit <- fit_copula(t1,t2,rclaytonCop);

copula_distance_test(t1,t2,cdf1,cdf2,indepCopula(),gumbelCopula(gfit$par))
copula_distance_test(t1,t2,cdf1,cdf2,claytonCopula(cfit$par),indepCopula())
copula_distance_test(t1,t2,cdf1,cdf2,indepCopula(),rotCopula(claytonCopula(rcfit$par),flip=c(TRUE,TRUE)))

copula_distance_test(t1,t2,cdf1,cdf2,claytonCopula(cfit$par),gumbelCopula(gfit$par))
copula_distance_test(t1,t2,cdf1,cdf2,claytonCopula(cfit$par),
                     rotCopula(claytonCopula(rcfit$par),flip=c(TRUE,TRUE)))

copula_distance_test(t1,t2,cdf1,cdf2,gumbelCopula(cfit$par),
                     rotCopula(claytonCopula(rcfit$par),flip=c(TRUE,TRUE)))
##########################################################################################
# Estimate the POWER of likelihood ratio test

nrep <- 200;
nobs <- 200;

t1 <- neurons[3,]
t2 <- neurons[2,]

# For independance copula(ez pz)
estim_test_error(nrep, nobs, t1,t2, indepCopula(), frankCopula(0.5),
                 function(x1,x2,cop0,cop1) copula_kramer_indep_test(x1,x2,nrep = 50),
                 type= 2
                 );
estim_test_error(nrep, nobs, t1,t2, indepCopula(), frankCopula(0.5),
                 function(x1,x2,cop0,cop1) copula_distance_test(x1,x2,cop0,cop1)
                 );
estim_test_error(nrep, nobs, t1,t2, indepCopula(), frankCopula(0.5),
                 function(x1,x2,cop0,cop1) copula_loglik_test(x1,x2,cop0,cop1,nrep=50)
                 );

##########################################################################################
# my loglikelihood difference test

data <- bin_neurons(c(3,2), 20);
t1 <- data[1,]
t2 <- data[2,]
nfit <- fit_copula(t1,t2,normalCopula());
gfit <- fit_copula(t1,t2,gumbelCopula(), upper=6);
cfit <- fit_copula(t1,t2,claytonCopula());

(c <- copula_loglik_test(t1,t2,indepCopula(),nfit$cop,alpha=0.6));

##########################################################################################
# generalized pseudo density funciton testing

t1 <- runif(10);
t2 <- runif(10);
F1 <- ecdf(t1);
F2 <- ecdf(t2);

pseudo_density(t1[1],t2[1],F1,F2,indepCopula(2))
generalized_pseudo_density(c(t1[1],t2[1]),c(F1,F2),indepCopula(2))
##########################################################################################
# Copula package statistical gof tests (don't use these the're for continious data)

t1 <- neurons[1,]
t2 <- neurons[2,]
xp <- cbind(ecdf(t1)(t1),ecdf(t2)(t2))
x <- pobs(cbind(t1,t2))
gumbel <- gofCopula(gumbelCopula(),x)

##########################################################################################
# Test paralell copula mle calculation

# Normal copula seems to take the longest
system.time(pairwise_copula_fit(neurons[1:10,], copula=normalCopula))

# Syncronous results:
#   user  system elapsed 
# 148.36    0.14  150.25 

# Asyncronous (with mcmapply from parallel package):
#   user  system elapsed 
# 146.50    0.04  147.33

# Well, that's under whelming
# It turns out that mcmapply isn't supported on windows... :(